services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ZjU5MDVmM2E4MjFiMTg3NmE1Y2FmMjg0YmUzOTc1M2Q=
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: laravel-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: laravel-db
    plan: free
